// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1wsBGFbpavP5keqD_8ZY1Irh-pH7w_Uc',
    appId: '1:615963216950:web:0eb485327d236a9e841c97',
    messagingSenderId: '615963216950',
    projectId: 'tamil-recipe-book',
    authDomain: 'tamil-recipe-book.firebaseapp.com',
    storageBucket: 'tamil-recipe-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQUMzWgM7_813BBxquXpjHcVo93b96-sY',
    appId: '1:615963216950:android:925bf3c9254e42cc841c97',
    messagingSenderId: '615963216950',
    projectId: 'tamil-recipe-book',
    storageBucket: 'tamil-recipe-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohsM_4Fv-BNZ8nqkgX6pi_3-UBYCNdMk',
    appId: '1:615963216950:ios:d98c57815604e4b1841c97',
    messagingSenderId: '615963216950',
    projectId: 'tamil-recipe-book',
    storageBucket: 'tamil-recipe-book.appspot.com',
    iosClientId: '615963216950-mqpb4gt58aode2g0sfdbnh2huj2bg760.apps.googleusercontent.com',
    iosBundleId: 'com.techashonline.tamilrecipebook.tamilRecipeBook',
  );
}
